# *Section 3: Operations on Two Matrices*
---------------------------------

## [25] Matrix Addition and Subtraction
 - Follows similar properties to real numbers
 
***Properties of Matrix Addition:***
- IS Commutative - you can add two matrices together in either order and still get the same answer A+B=B+A
- IS Associative - you can shift parentheses and get the same answer: A+(B+C) = (B+C)+A 

***Properties of Matrix Subtraction:***
- IS NOT Commutative - you can NOT add two matrices together in either order and still get the same answer A-B!=B-A
- IS NOT Associative - you can NOTift parentheses and get the same answer: A-(B-C) != (B-C)-A 

In [1]:
import numpy as np

a = np.matrix([[1, 2], 
               [3, 4]])

b = np.matrix([[2, 2], 
               [2, 2]])
display(a+b)

display(a-b)

matrix([[3, 4],
        [5, 6]])

matrix([[-1,  0],
        [ 1,  2]])

## [27] Scalar Multiplication
- Follows similar properties to real numbers
- Multiply the scalar by all values in matrix

In [1]:
import numpy as np

a = np.matrix([[1, 2], 
               [3, 4]])
display(5*a)

matrix([[ 5, 10],
        [15, 20]])

## [32]Matrix Multiplication
 - Use the **dot product** to multiply matrices
 - Matrices are able to be multiplied together if the inner numbers of the operation eg (2X**5** * **5**X4) are equal
 - The resultant dimensions are determined by the outer numbers eg(**2**X5 * 5X**4**) -> resultant dimension of 2X4
 
 
***Properties of Matrix Multiplication:***
- NOT Commutative
- IS Associative - you can shift parentheses and get the same answer
- IS Distributive - A(B+/-C) = AB +/- AC and (B+/-C)A = BA +/- CA 


In [12]:
import numpy as np
from sympy import Matrix

a = Matrix([[-2, 0],
     [1, 3],
           ])

b = Matrix([
    [-2, 1,2,3],
    [1,3,-2,-1],
           ]) 


#| 2(0)+3(0)=0  | 2(1)+3(-1)=-1  |
#| -1(0)+0(0)=0 | -1(1)+0(-1)=-1 |

c = Matrix(np.dot(a,b))
display(a,b)
display(c)

Matrix([
[-2, 0],
[ 1, 3]])

Matrix([
[-2, 1,  2,  3],
[ 1, 3, -2, -1]])

Matrix([
[4, -2, -4, -6],
[1, 10, -4,  0]])

In [3]:
import numpy as np
#Use the distributive property to find A(B+C)

a = np.matrix([[3, -1],
               [1, 4]])

b = np.matrix ([[5, 2],
                [-2, 3]]) 

c = np.matrix([[2, 0],
               [6, 2]]) 

display(a*(b+c))

matrix([[17,  1],
        [23, 22]])

##  [36]Elimination Matrix 
 - A matrix that produces REF when multiplied with a given matrix A
 - A^-1A = I
 - only applies to square matrices and the elimination matrix is the same dimension as A
 

In [8]:
my_integer = 10
my_float = 20.5
my_string = "Hello, Python!"
my_boolean = True

if  my_boolean:
  for i in range(my_integer):
    print(my_string*my_integer)

Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!
Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!
Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!
Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!
Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!
Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!
Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!Hello, Python!
Hello, Python